// NOTE: this test code is generated by LLM.

#include <decoterm/style.hpp>
#include <decoterm/styled.hpp>
#include <doctest.h>

#include <sstream>

namespace {

struct TestStyleOutputState : deco::StyleOutputState {
    using deco::StyleOutputState::pop_style;
    using deco::StyleOutputState::push_style;
    using deco::StyleOutputState::reset_style;
};

} // namespace

TEST_CASE("styled: StyleOutputState: options") {
    using namespace deco;

    StyleOutputState state;

    CHECK(state.style_enabled());
    CHECK_FALSE(state.color_fallback_enabled());
    CHECK_FALSE(state.nesting_enabled());
    CHECK(state.base_style() == default_style);
    CHECK(state.current_style().style == default_style);

    state.enable_style(false).enable_color_fallback(true).base_style(fg(blue));

    CHECK_FALSE(state.style_enabled());
    CHECK(state.color_fallback_enabled());
    CHECK(state.base_style() == fg(blue));
    CHECK(state.current_style().style == fg(blue));

    state.enable_nesting(true);
    CHECK(state.nesting_enabled());
    CHECK(state.current_style().style == fg(blue));

    state.enable_nesting(false);
    CHECK_FALSE(state.nesting_enabled());
    CHECK(state.current_style().style == fg(blue));
}

TEST_CASE("styled: StyleOutputState: single style state") {
    using namespace deco;

    TestStyleOutputState state;
    state.base_style(fg(blue));

    state.push_style(bold);
    CHECK(state.current_style().style == (fg(blue) | bold));

    state.push_style(fg(red));
    CHECK(state.current_style().style == (fg(red) | bold));

    state.pop_style();
    CHECK(state.current_style().style == fg(blue));

    state.push_style(absolute(fg(green)));
    CHECK(state.current_style().style == fg(green));

    state.reset_style();
    CHECK(state.current_style().style == fg(blue));
}

TEST_CASE("styled: StyleOutputState: nested style state") {
    using namespace deco;

    TestStyleOutputState state;
    state.base_style(fg(blue)).enable_nesting(true);

    state.push_style(bold);
    CHECK(state.current_style().style == (fg(blue) | bold));

    state.push_style(italic);
    CHECK(state.current_style().style == (fg(blue) | bold | italic));

    state.push_style(fg(red));
    CHECK(state.current_style().style == (fg(red) | bold | italic));

    state.pop_style();
    CHECK(state.current_style().style == (fg(blue) | bold | italic));

    state.pop_style();
    CHECK(state.current_style().style == (fg(blue) | bold));

    state.pop_style();
    CHECK(state.current_style().style == fg(blue));

    state.pop_style();
    CHECK(state.current_style().style == fg(blue));

    state.push_style(bold);
    state.reset_style();
    CHECK(state.current_style().style == fg(blue));
}


TEST_CASE("styled: StyledOstream: writes plain values") {
    using namespace deco;

    std::ostringstream os;
    StyledOstream styled_os(os);

    double d = 1.5;

    styled_os << "value=" << 42 << ' ' << d;

    CHECK(os.str() == "value=42 1.5");
}

TEST_CASE("styled: StyledOstream: writes styles") {
    using namespace deco;

    std::ostringstream os;
    StyledOstream styled_os(os);

    styled_os << fg(red) << "error" << reset;

    CHECK(os.str()
          == fg(red).to_escape() + std::string("error")
                 + absolute(default_style).to_escape());
}

TEST_CASE("styled: StyledOstream: can disable style output") {
    using namespace deco;

    std::ostringstream os;
    StyledOstream styled_os(os);
    styled_os.enable_style(false);

    styled_os << fg(red) << "error" << reset;

    CHECK(os.str() == "error");
    CHECK(styled_os.current_style().style == default_style);
}

TEST_CASE("styled: StyledOstream: restores nested styles") {
    using namespace deco;

    std::ostringstream os;
    StyledOstream styled_os(os);
    styled_os.base_style(fg(blue)).enable_nesting(true);

    styled_os << bold << "bold" << fg(red) << "red bold" << pop << "blue bold"
              << pop << "blue";

    CHECK(os.str()
          == bold.to_escape() + std::string("bold") + fg(red).to_escape()
                 + std::string("red bold")
                 + absolute(fg(blue) | bold).to_escape()
                 + std::string("blue bold") + absolute(fg(blue)).to_escape()
                 + std::string("blue"));
}

TEST_CASE("styled: StyledOstream: reset returns to base style") {
    using namespace deco;

    std::ostringstream os;
    StyledOstream styled_os(os);
    styled_os.base_style(fg(blue)).enable_nesting(true);

    styled_os << bold << "bold" << reset << "base";

    CHECK(os.str()
          == bold.to_escape() + std::string("bold")
                 + absolute(fg(blue)).to_escape() + std::string("base"));
}

// TEST_CASE("styled: StyledOstream: output same style twice ") {
//     using namespace deco;
//
//     std::ostringstream os;
//     StyledOstream styled_os(os);
//
//     styled_os << bold << bold;
//     CHECK(os.str() == bold.to_escape());
//
// }
