// NOTE: this test code is generated by LLM.

#include <decoterm/decoterm.hpp>
#include <doctest.h>

#include <format>
#include <iterator>
#include <string>
#include <string_view>

namespace {

auto esc(std::string_view params) -> std::string {
    std::string result = "\x1b[";
    result += params;
    result += 'm';
    return result;
}

auto sgr_params(deco::Style style) -> std::string {
    std::string result;
    style.to_sgr_params(std::back_inserter(result));
    return result;
}

} // namespace

TEST_CASE("Style::to_sgr_params writes separators only between parameters") {
    using namespace deco;

    CHECK(sgr_params(Style()) == "");
    CHECK(sgr_params(bold) == "1");
    CHECK(sgr_params(bold | italic | underline) == "1;3;4");
    CHECK(sgr_params(fg(red) | bg(blue)) == "31;44");
    CHECK(sgr_params(fg(rgb(1, 2, 3)) | bg(rgb(4, 5, 6))) ==
          "38;2;1;2;3;48;2;4;5;6");
    CHECK(sgr_params(bold | fg(red) | bg(blue) | underline) == "31;44;1;4");
}

TEST_CASE("Style composition merges flags and lets rhs colors override") {
    using namespace deco;

    const Style composed = fg(red) | bg(blue) | bold | fg(green) | italic;

    CHECK(composed.flags == (Style::Bold | Style::Italic));
    CHECK(composed.fg == green);
    CHECK(composed.bg == blue);
    CHECK(sgr_params(composed) == "32;44;1;3");

    const Style rhs_without_colors = fg(red) | bg(blue) | bold;
    CHECK((rhs_without_colors | italic).fg == red);
    CHECK((rhs_without_colors | italic).bg == blue);
    CHECK(sgr_params(rhs_without_colors | italic) == "31;44;1;3");
}

TEST_CASE("Style::to_escape wraps SGR params") {
    using namespace deco;

    CHECK(Style().to_escape() == esc(""));
    CHECK((fg(red) | bg(blue) | bold).to_escape() == esc("31;44;1"));
}

TEST_CASE("Style formatter writes escape sequences") {
    using namespace deco;

    CHECK(std::format("{}text", fg(red) | bg(blue) | bold) ==
          esc("31;44;1") + "text");
    CHECK(std::format("{}", Style()) == esc(""));
}
