# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: make-single-header
        name: make "single-header/decoterm.hpp"
        language: python
        entry: python scripts/make_single_header.py
        pass_filenames: false
